#!/bin/sh

#SBATCH --job-name=lay3_55

#SBATCH --output=BnB.o

#SBATCH --error=BnB.error

#SBATCH --partition=savio2

#SBATCH --time=72:00:00

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=28

# QoS:

#SBATCH --qos=savio_normal

#

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
# setenv OMP_NUM_THREAD 28

# mpirun -np 2 --map-by ppr:1:node:pe=28 ~/bin/sss2/sss2_mpi -omp 28 BnB
~/bin/sss2/sss2_mpi -omp 28 BnB